#!/usr/bin/env python2.6

# vim: tabstop=4 shiftwidth=4 softtabstop=4

# Copyright (c) 2011 Citrix Systems, Inc.
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

import os
import re
import shutil
import socket
import sys
import xmlrpclib

from geppetto.geppettolib import network
from geppetto.geppettolib import utils
from geppetto.geppettolib.puppet import PuppetNode

# Set connection timeout to 30 secs
socket.setdefaulttimeout(30)

# Set django settings as it's required by service_proxy
os.environ['DJANGO_SETTINGS_MODULE'] = 'geppetto.core'

from geppetto.core.views import service_proxy


RUBY_LIB = '/tmp/ruby'
FACTER_PATH = '%s/facter' % RUBY_LIB
LAST_FACTS = '/tmp/facts.lastsrun'

EXCLUDE_FACTS = ['uptime', 'uptime_seconds', 'memoryfree']


def write_facts(facts):
    try:
        with open(LAST_FACTS, 'w') as f:
            f.write(facts)
    except IOError, e:
        print >> sys.stderr, e


def read_facts():
    try:
        with open(LAST_FACTS, 'r') as f:
            return f.read()
    except IOError, e:
        print >> sys.stderr, e
        return ''


def are_facts_changed(facts):
    last_facts = read_facts()
    if last_facts == facts:
        return False
    else:
        write_facts(facts)
        return True


def strip_facts_entries(facts, exclude_list=EXCLUDE_FACTS):
    for entry in exclude_list:
        facts = re.sub('%s: .*' % entry, '', facts)
    return facts


if __name__ == "__main__":
    try:
        os.environ['RUBYLIB'] = RUBY_LIB
        if not os.path.exists(FACTER_PATH):
            shutil.copytree('/var/lib/puppet/facts/', FACTER_PATH)

        custom_fact = len(sys.argv) == 2 and sys.argv[1] or ''
        facter_cmd = 'facter %s' % custom_fact
        facts, err = utils.execute(facter_cmd)
        facts = facts.replace(' => ', ': ')
        facts = strip_facts_entries(facts)
        if are_facts_changed(facts):
                master_fqdn = PuppetNode.get_puppet_option('server')
                proxy = service_proxy.create_proxy(master_fqdn, 8080,
                                                   service_proxy.Proxy.Facter)
                proxy.process_facts(network.get_hostname().lower(), facts)
                print facts
        else:
            print >> sys.stderr, ('No changes occurred, to see the facts '
                                 'check the file: %s') % LAST_FACTS
        sys.exit(0)
    except xmlrpclib.ProtocolError, err:
        print >> sys.stderr, "A protocol error occurred"
        print >> sys.stderr, "URL: %s" % err.url
        print >> sys.stderr, "HTTP/HTTPS headers: %s" % err.headers
        print >> sys.stderr, "Error code: %d" % err.errcode
        print >> sys.stderr, "Error message: %s" % err.errmsg
        sys.exit(1)
    except Exception, err:
        print >> sys.stderr, err
        sys.exit(2)
