#!/bin/bash

# This script is used to generate a simple /etc/rndc.key
# Please make sure to call this script ahead of any
# DHCP/DNS configuration
#

RNDC_KEY_FILE=/usr/share/geppetto/rndc.key

generate_secret()
{
  # using urandom is less secure, but it prevents the command from hanging 
  # waiting for more entropy
  cd /usr/share/geppetto/ > /dev/null
  KEY_NAME=`dnssec-keygen -a HMAC-MD5 -b 512 -n HOST -r /dev/urandom temp_key.net`
  echo `cat  $KEY_NAME.private | grep Key | awk '{print $2}'`
  rm -rf *temp_key.net*
  cd - > /dev/null
}

generate_key_file()
{
  cat > $RNDC_KEY_FILE << EOF
# This key file  is automatically generated by Geppetto, please do not edit.

key "rndckey" {
        algorithm       hmac-md5;
        secret          "$1";
};
EOF
chmod a+r $RNDC_KEY_FILE
}

SECRET=$(generate_secret)
generate_key_file $SECRET

